## YAML Template.
language: java

addons:
    sonarcloud:
        organization: "jramirezl-github"
        token:
            secure: Iisw3gAf23xipW9K1FCkxoingKxl5H9vvY6uWDiP/6rV0y13mTVyeNUTrDDrdgTEIrGCQT2FZcCgiZlytDAMbvQHTF5+GlInD3aaPr6RMAKT7qnTw7vriqsSvApC+xLMhYjzwUgHFtKkwQvY118p01o6TdmSawzeP1mJMnf7bTgOvExFEVrJrKZjL0IL6t1YX5R5Eb64IE3BL0328D0R0Xr2mrFIkikLz2qet33vZt1PZy/LO9/V6ERk23s1772X5QZs5ttqEcz+Pr4cT8OpbiD1jSV+TcQUUslRDsdohLtxiY0CjpmdQ+ZtlLazqtYkh5Z0G76P+4AU8nRE0o/1D13Zb7iwxHXkoBGnVY8LVwW2yYyo4gcWxXnEJ6mLHCjstuibIDufGvVMqVispi88xJzm5BooACIWc9irZh5HY7mLxvaVaJ8ti5iNPaL85bJajq2TzfznP+faQZlShrdq/43Sz8ChOaUxtaN5YKXqTZ5mHeOIfecph4CLVwHi5KwRfjyLwE1aFW8sAqOWcKnI8A1L/9vxvM50AWbPWytLpy3iuE/DCLYgCi/l3szH7d1UD+ouZSVlIPrztHyy8RqhR1puivzHyJFY5D8ndlh3FCnkzjfRAlwwgvUpMQ2dRn/u+jE12M5jjwCIOpOdxcpQe2YnZMr3jOS7o9ArVGBXi4A=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
