## YAML Template.
language: java
addons:
    sonarcloud:
        organization: javalenjara-github
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${e7b3171f12893be80412c5c0e80a190da193a91f}
