## YAML Template.
language: java

addons:
    sonarcloud:
        organization: "javalenjara-github"
        token:
            secure: j0DvEAoMFmDNPHNZrgoXSZxN14cpQwWMMMqspCHfKsY/TpC6EDq7XlLRvVvan/j8l7yp7fXPk0abCF5jmZiYeGBmcqNDRb9lIp95J0XuI9ZQmYgrsZWLTpNQUrUYjDujhMk7SQTgDv/0WFfmpa2K2i1hzVCfuPp5YeEWvVAW/tb1n1EY0ZDXakdtNmE36j0BpaaooFulzw49Ez4IWL+ug8U/EG2eBLQ85o5ouTrxSfYpnimo82PLLNsf0XWCZ8UMpZtAq4Bwcr62LOmQORKcQaJcaGOrdq9DnUnvHgekJ/Vffo7alichbhbIs5AoA70Ik9cNgod9FZUrC+BT48JLhFm7/Rk7rnmedINQuibw571u00zO8jUs5/YvBJidWpqPz1vziGfi+h+ZoEnmQcI0jNWCiL4jPfW+uyI1k9tJzyUmeltfw47DRHqtcPkP9NKLDqZ2NemQm9fytivK38MdY7kPWtZUYSun4QcMtUH7WQsQp/IjhfZo78Jtwur466UHt6pGge3gyV7QPmJPA/W26EL4yy8SH6IsOxkBX+D7OMT1imBaPk3uB6AWhTIBZqlWeOeUQBC971hZEAcY/sK/dQIgwn1CuEoo+1jfk7TNLK/hr/TbWktI73wjwofeSm4BeqakDzmTL/sqCqOs01asP8+7rGAorTleR0aUmlJN1O0=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
